/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.sql.*;
import java.awt.event.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dangd
 */
public class forgotForm extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    public forgotForm() {
        initComponents();
        conn = MyConnection.getConnection();
        mainPanel.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        lblRecovery = new javax.swing.JLabel();
        lblUserId = new javax.swing.JLabel();
        txtFieldUserId = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtFieldName = new javax.swing.JTextField();
        lblQuestion = new javax.swing.JLabel();
        txtFieldQuestion = new javax.swing.JTextField();
        lblAnswer = new javax.swing.JLabel();
        txtFieldAnswer = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtFieldPassword = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnRecover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 3, 2, new java.awt.Color(153, 153, 153)));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));

        headerPanel.setBackground(new java.awt.Color(0, 255, 0));
        headerPanel.setForeground(new java.awt.Color(0, 255, 0));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblX.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblX.setForeground(new java.awt.Color(255, 255, 255));
        lblX.setText("X");
        lblX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXMouseClicked(evt);
            }
        });
        headerPanel.add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, 30));

        lblRecovery.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRecovery.setForeground(new java.awt.Color(255, 255, 255));
        lblRecovery.setText("Recovery!");
        headerPanel.add(lblRecovery, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        lblUserId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserId.setForeground(new java.awt.Color(153, 153, 153));
        lblUserId.setText("User ID :");

        txtFieldUserId.setBackground(new java.awt.Color(255, 255, 255));
        txtFieldUserId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFieldUserId.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldUserId.setText("        Enter Username to Search");
        txtFieldUserId.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));
        txtFieldUserId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFieldUserIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFieldUserIdFocusLost(evt);
            }
        });
        txtFieldUserId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldUserIdKeyPressed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(153, 153, 153));
        lblName.setText("Name :");

        txtFieldName.setBackground(new java.awt.Color(255, 255, 255));
        txtFieldName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFieldName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblQuestion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuestion.setForeground(new java.awt.Color(153, 153, 153));
        lblQuestion.setText("Sequrity Question :");

        txtFieldQuestion.setBackground(new java.awt.Color(255, 255, 255));
        txtFieldQuestion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFieldQuestion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblAnswer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAnswer.setForeground(new java.awt.Color(153, 153, 153));
        lblAnswer.setText("Answer :");

        txtFieldAnswer.setBackground(new java.awt.Color(255, 255, 255));
        txtFieldAnswer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFieldAnswer.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(153, 153, 153));
        lblPassword.setText("Password :");

        txtFieldPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtFieldPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtFieldPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(153, 153, 153)));

        btnBack.setBackground(new java.awt.Color(255, 0, 51));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Go Back");
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRecover.setBackground(new java.awt.Color(0, 255, 0));
        btnRecover.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRecover.setForeground(new java.awt.Color(255, 255, 255));
        btnRecover.setText("Recover");
        btnRecover.setBorderPainted(false);
        btnRecover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFieldAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRecover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPassword)
                            .addComponent(lblAnswer)
                            .addComponent(lblQuestion)
                            .addComponent(lblName)
                            .addComponent(lblUserId)
                            .addComponent(txtFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUserId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAnswer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRecover, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXMouseClicked
        dispose();
    }//GEN-LAST:event_lblXMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        loginForm l = new loginForm();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtFieldUserIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldUserIdFocusGained

        if (txtFieldUserId.getText().trim().equals("Enter Username to Search")) {
            txtFieldUserId.setText("");
        }
        txtFieldUserId.setForeground(Color.BLACK);
    }//GEN-LAST:event_txtFieldUserIdFocusGained

    private void txtFieldUserIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFieldUserIdFocusLost

        if (txtFieldUserId.getText().trim().equals("")) {
            txtFieldUserId.setText("        Enter Username to Search");
            txtFieldName.setText("");
            txtFieldQuestion.setText("");
            txtFieldAnswer.setText("");
            txtFieldPassword.setText("");
        }
        txtFieldUserId.setForeground(new Color(153, 153, 153));
    }//GEN-LAST:event_txtFieldUserIdFocusLost

    private void btnRecoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecoverActionPerformed
        String ans = txtFieldAnswer.getText();
        if (ans.equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill the answer to retrieve Password");
        } else {
            String sq = "SELECT * FROM `user` WHERE `ans`='"+ans+"'";
            try {
                ps = conn.prepareStatement(sq);
                rs = ps.executeQuery();
                if (rs.next()) {
                    String answer = rs.getString(2);
                    txtFieldPassword.setText("Your Password is: " + answer);
                } else {
                    JOptionPane.showMessageDialog(null, "Answer is not matched with database!");
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

        }
    }//GEN-LAST:event_btnRecoverActionPerformed

    private void txtFieldUserIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldUserIdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String sql = "SELECT * FROM `user` WHERE `username` = ?";
            try {
                ps = conn.prepareStatement(sql);
                ps.setString(1, txtFieldUserId.getText());
                rs = ps.executeQuery();
                if (rs.next()) {
                    txtFieldName.setText(rs.getString("fname"));
                    txtFieldQuestion.setText(rs.getString("ques"));
                } else {
                    JOptionPane.showMessageDialog(null, "Username not found in database");

                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }

    }//GEN-LAST:event_txtFieldUserIdKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRecover;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblRecovery;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JLabel lblX;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField txtFieldAnswer;
    private javax.swing.JTextField txtFieldName;
    private javax.swing.JTextField txtFieldPassword;
    private javax.swing.JTextField txtFieldQuestion;
    private javax.swing.JTextField txtFieldUserId;
    // End of variables declaration//GEN-END:variables
}
